-- Q1. IMPORT THE TEST.SQL FILE AND SOLVE THE FOLLOWING QUERIES –                                                       
--         [25 MARKS] 
 
-- 1. DISPLAY STUDENT NO. AND TOTAL MARKS OF EACH STUDENT HAVING TOTAL MARKS GREATER 
-- THAN 160. 
 
-- 2. DISPLAY STUDENT NAME (FORENAME + SURNAME), MODULE NAME, AND MARK OF STUDENTS 
-- HAVING MARK GREATER THAN THE MARK OF EMILE ZOLA IN THE DATABASES MODULE USING 
-- JOINS. 
 
-- 3. CREATE A FOREIGN KEY CONSTRAINT ON THE ‘STUDENT_NO’ COLUMN OF THE MARKS TABLE 
-- ASSUMING ‘STUDENT_NO’ IS THE PRIMARY KEY OF THE STUDENT TABLE. 
 
-- 4. WRITE A FUNCTION TO TAKE THE INPUT AS MARK AND RETURN THE GRADE. 
-- GRADE IS A IF MARK IS 80 AND ABOVE 
-- ELSE GRADE IS B IF MARK IS IN RANGE 65 TO 80 
-- ELSE GRADE IS C IF MARK IS IN RANGE 50 TO 64 
-- OTHERWISE, FAIL IF MARK < 50. 
 
-- 5. WRITE A STORED PROCEDURE TO DISPLAY ALL THE TABLES WHOSE NAME STARTS WITH M. 
 
 
 
 
-- Q2. IMPORT THE EMP.CSV FILE AND SOLVE THE FOLLOWING QUERIES USING MONGODB –                        
--         [15 MARKS] 
 
-- 1. DISPLAY EMPLOYEE NAME WHOSE SALARY(SAL) GREATER THAN 2000. 
 
-- 2. INSERT A RECORD IN THE EMP COLLECTION. (ASSUME EMPLOYEE DETAILS)  
 
-- 3. DELETE THE RECORD OF THE EMPLOYEE WHOSE NAME IS FORD.