 DROP FUNCTION IF EXISTS SalSum;

 DELIMITER &&

 CREATE FUNCTION SalSum(id INT)

 RETURNS INT 
 DETERMINISTIC

 BEGIN
    DECLARE sal_sum INT;
    SELECT SUM(SALARY) AS TOTAL_SAL into sal_sum 
    FROM worker GROUP BY DEPARTMENT 
    HAVING DEPARTMENT = (SELECT DEPARTMENT FROM worker WHERE WORKER_ID=id);
    return sal_sum;
 END;

 &&
 
 DELIMITER ;