 DROP FUNCTION IF EXISTS MarkToGrade;

 DELIMITER &&
 
 CREATE FUNCTION MarkToGrade(mark INT)
 
 RETURNS VARCHAR(4)
 DETERMINISTIC

 BEGIN
  DECLARE grade VARCHAR(4);
  IF Mark >= 80 THEN
    RETURN 'A'
  ELSE IF Mark >= 65 AND Mark < 80 THEN
    RETURN 'B'
  ELSE IF Mark >= 50 AND Mark < 65 THEN
    RETURN 'C'
  ELSE 
    RETURN 'FAIL' 
 END;
 &&

 DELIMITER ;